// This file was @generated by typegen
export type FileMetadata = Text | Image | Video | Other;

export interface Text {
  type: "Text";
}

export interface Image {
  type: "Image";
  width: number | null;
  height: number | null;
}

export interface Video {
  type: "Video";
  width: number | null;
  height: number | null;
}

export interface Other {
  type: "Other";
}
/** Represents information about the connected Eludris instance.

-----

### Example

```json
{
  "instance_name": "eludris",
  "description": "The *almost* official Eludris instance - ooliver.",
  "version": "0.3.2",
  "message_limit": 2000,
  "oprish_url": "https://api.eludris.gay",
  "pandemonium_url": "wss://ws.eludris.gay/",
  "effis_url": "https://cdn.eludris.gay",
  "file_size": 20000000,
  "attachment_file_size": 25000000,
  "rate_limits": {
    "oprish": {
      "info": {
        "reset_after": 5,
        "limit": 2
      },
      "message_create": {
        "reset_after": 5,
        "limit": 10
      },
      "rate_limits": {
        "reset_after": 5,
        "limit": 2
      }
    },
    "pandemonium": {
      "reset_after": 10,
      "limit": 5
    },
    "effis": {
      "assets": {
        "reset_after": 60,
        "limit": 5,
        "file_size_limit": 30000000
      },
      "attachments": {
        "reset_after": 180,
        "limit": 20,
        "file_size_limit": 500000000
      },
      "fetch_file": {
        "reset_after": 60,
        "limit": 30
      }
    }
  }
}
``` */
export interface InstanceInfo {
  /** The name of the instance. */
  instance_name: string;
  /** The description of the instance.

  This is between 1 and 2048 characters long. */
  description: string | null;
  /** The Eludris version the instance is running. */
  version: string;
  /** The maximum length of a message's content. */
  message_limit: number;
  /** The URL of the instance's Oprish (REST API) endpoint. */
  oprish_url: string;
  /** The URL of the instance's Pandemonium (WebSocket API) endpoint. */
  pandemonium_url: string;
  /** The URL of the instance's Effis (CDN) endpoint. */
  effis_url: string;
  /** The maximum file size (in bytes) of an asset. */
  file_size: number;
  /** The maximum file size (in bytes) of an attachment. */
  attachment_file_size: number;
  /** The rate limits that apply to the connected Eludris instance.

  This is not present if the `rate_limits` query parameter is not set. */
  rate_limits: InstanceRateLimits | null;
}
/** Represents a file stored on Effis.

-----

### Example

```json
{
  "id": 2195354353667,
  "name": "das_ding.png",
  "bucket": "attachments",
  "metadata": {
    "type": "image",
    "width": 1600,
    "height": 1600
  }
}
``` */
export interface FileData {
  /** The ID of the file. */
  id: number;
  /** The name of the file. */
  name: string;
  /** The bucket the file is stored in. */
  bucket: string;
  /** If the file is spoilered. */
  spoiler: boolean;
  /** The {@link FileMetadata} of the file. */
  metadata: FileMetadata;
}
/** The message payload.

-----

### Example

```json
{
  "author": "Not a weeb",
  "content": "Hello, World!"
}
``` */
export interface Message {
  /** The author of message. This field has to be between 2 and 32 characters long.

  The author will be trimmed from leading and trailing whitespace. */
  author: string;
  /** The content of the message. This field has to be at-least 2 characters long. The upper limit
  is the instance's {@link InstanceInfo} `message_limit`.

  The content will be trimmed from leading and trailing whitespace. */
  content: string;
}
/** Represents a single rate limit for Effis.

-----

### Example

```json
{
  "reset_after": 60,
  "limit": 5,
  "file_size_limit": 30000000
}
``` */
export interface EffisRateLimitConf {
  /** The amount of seconds after which the rate limit resets. */
  reset_after: number;
  /** The amount of requests that can be made within the `reset_after` interval. */
  limit: number;
  /** The maximum amount of bytes that can be sent within the `reset_after` interval. */
  file_size_limit: number;
}
/** Represents a single rate limit.

-----

### Example

```json
{
  "reset_after": 60,
  "limit": 30
}
``` */
export interface RateLimitConf {
  /** The amount of seconds after which the rate limit resets. */
  reset_after: number;
  /** The amount of requests that can be made within the `reset_after` interval. */
  limit: number;
}
/** Represents all rate limits that apply to the connected Eludris instance.

-----

### Example
```json
{
  "oprish": {
    "info": {
      "reset_after": 5,
      "limit": 2
    },
    "message_create": {
      "reset_after": 5,
      "limit": 10
    },
    "rate_limits": {
      "reset_after": 5,
      "limit": 2
    }
  },
  "pandemonium": {
    "reset_after": 10,
    "limit": 5
  },
  "effis": {
    "assets": {
      "reset_after": 60,
      "limit": 5,
      "file_size_limit": 30000000
    },
    "attachments": {
      "reset_after": 180,
      "limit": 20,
      "file_size_limit": 500000000
    },
    "fetch_file": {
      "reset_after": 60,
      "limit": 30
    }
  }
}
``` */
export interface InstanceRateLimits {
  /** Rate limits for Oprish (The REST API). */
  oprish: OprishRateLimits;
  /** Rate limits for Pandemonium (The WebSocket API). */
  pandemonium: RateLimitConf;
  /** Rate limits for Effis (The CDN). */
  effis: EffisRateLimits;
}
export type ServerPayload = Pong | RateLimit | Hello | MessageCreate;
/** Rate limits that apply to Oprish (The REST API).

-----

### Example

```json
{
  "get_instance_info": {
    "reset_after": 5,
    "limit": 2
  },
  "create_message": {
    "reset_after": 5,
    "limit": 10
  }
}
``` */
export interface OprishRateLimits {
  /** Rate limits for the {@link get_instance_info} endpoint. */
  get_instance_info: RateLimitConf;
  /** Rate limits for the {@link create_message} endpoint. */
  create_message: RateLimitConf;
}
/** Rate limits that apply to Effis (The CDN).

-----

### Example

```json
{
  "assets": {
    "reset_after": 60,
    "limit": 5,
    "file_size_limit": 30000000
  },
  "attachments": {
    "reset_after": 180,
    "limit": 20,
    "file_size_limit": 500000000
  },
  "fetch_file": {
    "reset_after": 60,
    "limit": 30
  }
}
``` */
export interface EffisRateLimits {
  /** Rate limits for the asset buckets. */
  assets: EffisRateLimitConf;
  /** Rate limits for the attachment bucket. */
  attachments: EffisRateLimitConf;
  /** Rate limits for the file fetching endpoints. */
  fetch_file: RateLimitConf;
}
/** The data format for uploading a file.

This is a `multipart/form-data` form.

-----

### Example

```sh
curl \
  -F file=@trolley.mp4 \
  -F spoiler=true \
  https://cdn.eludris.gay/attachments/
``` */
export interface FileUpload {
  file: unknown;
  spoiler: boolean;
}
/** A {@link ClientPayload} `PING` payload response.

-----

### Example

```json
{
  "op": "PONG"
}
``` */
export interface Pong {
  op: "PONG";
}
/** The event sent when the client gets gateway rate limited.

The client is supposed to wait `wait` milliseconds before sending any more events,
otherwise they are disconnected.

-----

### Example

```json
{
  "op": "RATE_LIMIT",
  "d": {
    "wait": 1010 // 1.01 seconds
  }
}
``` */
export interface RateLimit {
  op: "RATE_LIMIT";
  wait: number;
}
/** The payload sent by the server when you initiate a new gateway connection.

-----

### Example

```json
{
  "op": "HELLO",
  "d": {
    "heartbeat_interval": 45000,
    "instance_info": {
      "instance_name": "EmreLand",
      "description": "More based than Oliver's instance (trust)",
      "version": "0.3.3",
      "message_limit": 2048,
      "oprish_url": "https://example.com",
      "pandemonium_url": "https://example.com",
      "effis_url": "https://example.com",
      "file_size": 20000000,
      "attachment_file_size": 100000000
    },
    "rate_limit": {
      "reset_after": 10,
      "limit": 5
    }
  }
}
``` */
export interface Hello {
  op: "HELLO";
  heartbeat_interval: number;
  instance_info: InstanceInfo;
  rate_limit: RateLimitConf;
}
/** The event sent when the client receives a {@link Message}.

-----

### Example

```json
{
  "op": "MESSAGE_CREATE",
  "d": {
    "author": "A Certain Woo",
    "content": "Woo!"
  }
}
``` */
export interface MessageCreate {
  op: "MESSAGE_CREATE";
  d: Message;
}
/** Shared fields between all error response variants. */
export interface SharedErrorData {
  /** The HTTP status of the error. */
  status: number;
  /** A brief explanation of the error. */
  message: string;
}
export type ClientPayload = Ping;
/** The payload the client is supposed to periodically send the server to not get disconnected.

The interval where these pings are supposed to be sent can be found in the `HELLO` payload
of the {@link ServerPayload} enum.

-----

> **Note**
>
> You are supposed to send your first ping in a connection after `RAND * heartbeat_interval` seconds,
`RAND` being a random floating number between 0 and 1.
>
> This is done to avoid immediately overloading Pandemonium by connecting if it ever has to go down.

### Example

```json
> {"op":"PING"}
< {"op":"PONG"}
``` */
export interface Ping {
  op: "PING";
}
export type ErrorResponse = RateLimited | Validation | NotFound | Server;
/** The error when a client is rate limited.

------

### Example

```json
{
  "type": "RATE_LIMITED",
  "status": 429,
  "message": "You have been rate limited",
  "retry_after": 1234
}
``` */
export interface RateLimited extends SharedErrorData {
  type: "RATE_LIMITED";
  retry_after: number;
}
/** The error when a request a client sends is incorrect and fails validation.

-----

### Example

```json
{
  "type": "VALIDATION",
  "status": 422,
  "message": "Invalid request",
  "value_name": "author",
  "info": "author name is a bit too cringe"
}
``` */
export interface Validation extends SharedErrorData {
  type: "VALIDATION";
  value_name: string;
  info: string;
}
/** The error when a client requests a resource that does not exist.

-----

### Example

```json
{
  "type": "NOT_FOUND",
  "status": 404,
  "message": "The requested resource could not be found"
}
``` */
export interface NotFound extends SharedErrorData {
  type: "NOT_FOUND";
}
/** The error when the server fails to process a request.

Getting this error means that it's the server's fault and not the client that the request
failed.

-----

### Example

```json
{
  "type": "SERVER",
  "status": 500,
  "message": "Server encountered an unexpected error",
  "info": "Server got stabbed 28 times"
}
``` */
export interface Server extends SharedErrorData {
  type: "SERVER";
  info: string;
}
